version: "3.6"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
    volumes:
      - db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - $MONGO_EXPRESS_UI_LOCAL_PORT:$MONGO_EXPRESS_UI_DOCKER_PORT
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_SERVER: $MONGODB_DOCKER_SERVER_NAME

volumes:
  db:
    driver: local
